[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[BufferedStreams]]
deps = ["Compat", "Pkg", "Test"]
git-tree-sha1 = "0564a7fd529abf18afb644d7d73c30771988b5be"
uuid = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
version = "0.4.1"

[[CategoricalArrays]]
deps = ["Compat", "Future", "JSON", "Missings", "Printf", "Reexport"]
git-tree-sha1 = "903ab7490d404e313fc9bf53942e28b1ba9307e8"
uuid = "324d7699-5711-5eae-9e2f-1d82baa6b597"
version = "0.3.11"

[[CodecZlib]]
deps = ["BinaryProvider", "Compat", "Test", "TranscodingStreams"]
git-tree-sha1 = "82742ef572290f566c6fc6d977d87586a0d3d5f1"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.4.3"

[[Codecs]]
deps = ["Compat"]
git-tree-sha1 = "511ccd52570f94e45022ef9698146722d4f1f94d"
uuid = "19ecbf4d-ef7c-5e4b-b54a-0a0ff23c5aed"
version = "0.4.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "c478aec93ea90bb99c307a92df17a76131bf275f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.0"

[[Crayons]]
deps = ["InteractiveUtils", "Pkg", "Test"]
git-tree-sha1 = "23a96d0f0eeaf8d82cb0dc8b618f7385aeeb5071"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "0.5.1"

[[DataFrames]]
deps = ["CategoricalArrays", "CodecZlib", "Compat", "DataStreams", "Dates", "InteractiveUtils", "LinearAlgebra", "Missings", "Printf", "Random", "Reexport", "SortingAlgorithms", "Statistics", "StatsBase", "Test", "TranscodingStreams", "Unicode", "WeakRefStrings"]
git-tree-sha1 = "1cc9493d9b659db1fa6d584afc3f73d74341e567"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "0.12.0"

[[DataStreams]]
deps = ["Compat", "Missings", "NamedTuples", "WeakRefStrings"]
git-tree-sha1 = "62d1a39a3e9634eceb7413151b48cbc95521a059"
uuid = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
version = "0.3.6"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[DataValues]]
deps = ["Dates", "InteractiveUtils", "LinearAlgebra", "Nullables", "Random", "Test"]
git-tree-sha1 = "f766ea2c2bbf1338c432556ef0dafae4aadffe47"
uuid = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
version = "0.4.2"

[[DateParser]]
deps = ["TimeZones"]
git-tree-sha1 = "ba05c12c1fa2496f78760a62da0d67d29035d9e2"
uuid = "c513aa4d-7626-5656-a882-4604be010eff"
version = "0.1.1"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DecFP]]
deps = ["BinaryProvider", "Compat", "SpecialFunctions"]
git-tree-sha1 = "c35de244ab5b6c5c626f0a393240dbde3e35f723"
uuid = "55939f99-70c6-5e9b-8bb0-5071ed7d61fd"
version = "0.4.5"

[[Decimals]]
deps = ["Compat"]
git-tree-sha1 = "6eba63c98f87e99dc15b1715cd996a8368ca4df0"
uuid = "abce61dc-4473-55a0-ba07-351d65e31d42"
version = "0.3.0"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["Compat"]
git-tree-sha1 = "0d767d338c201b1b2064e2186a0b63ac1e55dbb1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.4.5"

[[EzXML]]
deps = ["BinaryProvider", "Compat", "Test"]
git-tree-sha1 = "859a6fffaf14bf882a94ad1dc270fedef791366e"
uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
version = "0.7.1"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[HTTPClient]]
deps = ["Compat", "LibCURL"]
git-tree-sha1 = "161d5776ae8e585ac0b8c20fb81f17ab755b3671"
uuid = "0862f596-cf2d-50af-8ef4-f2be67dfa83f"
version = "0.2.1"

[[Homebrew]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "Unicode"]
git-tree-sha1 = "b8503955180201f902cc23dc0c299584c859f545"
uuid = "d9be37ee-ecc9-5288-90f1-b9ca67657a75"
version = "0.6.4"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IterTools]]
deps = ["Pkg", "SparseArrays", "Test"]
git-tree-sha1 = "ed0787e62dc46b8d8c7c3db54391d71e0da5fefd"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.0.0"

[[IterableTables]]
deps = ["DataValues", "IteratorInterfaceExtensions", "Requires", "TableTraits", "TableTraitsUtils", "Test"]
git-tree-sha1 = "1621542fcf5873f96fad488057078218a870608a"
uuid = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
version = "0.8.1"

[[IteratorInterfaceExtensions]]
deps = ["Test"]
git-tree-sha1 = "0c41964e8383281ee837dcd034148ab83ff6154e"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "0.1.0"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LayerDicts]]
deps = ["Compat"]
git-tree-sha1 = "d8e6435d3aa9e239bce6cad441278d46f4f13f21"
uuid = "6f188dcb-512c-564b-bc01-e0f76e72f166"
version = "0.1.1"

[[LegacyStrings]]
deps = ["Compat"]
git-tree-sha1 = "c06e053a42518b5509c8db7d014a0fa3410b2f0d"
uuid = "1b4a561d-cfcb-5daf-8433-43fcf8b4bea3"
version = "0.3.0"

[[LibCURL]]
deps = ["BinDeps", "Compat", "Libdl", "WinRPM"]
git-tree-sha1 = "9b431bc66757ad5124f4d206c319996a2dfa2662"
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.2.2"

[[LibExpat]]
deps = ["Compat"]
git-tree-sha1 = "8ba2ca1635ec1755bcf1432c9a2aa6c91a3fb4fd"
uuid = "522f3ed2-3f36-55e3-b6df-e94fee9b0c07"
version = "0.4.2"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[LibPQ]]
deps = ["BinaryProvider", "Compat", "DataStreams", "Decimals", "DocStringExtensions", "IterTools", "LayerDicts", "Memento", "Missings", "OffsetArrays", "TimeZones"]
git-tree-sha1 = "268a42d5267508694f73008abc484b91f84c1651"
repo-rev = "master"
repo-url = "https://github.com/invenia/LibPQ.jl.git"
uuid = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
version = "0.3.0+"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libz]]
deps = ["BufferedStreams", "Compat"]
git-tree-sha1 = "f26ee67f03d71be4633b21634755bc58e2457091"
uuid = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
version = "0.4.0"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Lumberjack]]
deps = ["Compat", "JSON", "Mocking", "StackTraces"]
git-tree-sha1 = "f1a2279ff2d20133958feab65ca953e75a207caf"
repo-rev = "master"
repo-url = "https://github.com/WestleyArgentum/Lumberjack.jl.git"
uuid = "ff7a09a4-2bbe-5ce1-96cb-a4b0cacc22b1"
version = "2.1.1+"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[MbedTLS]]
deps = ["BinaryProvider", "Compat", "Sockets"]
git-tree-sha1 = "9c6b927293e9133277d8c99f06ab3d5470b34572"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "0.5.12"

[[Memento]]
deps = ["Compat", "JSON", "Nullables", "Syslogs"]
git-tree-sha1 = "fb72f98eb7752f00e32f593c74f2e566ebf7061b"
uuid = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
version = "0.9.0"

[[Millboard]]
deps = ["Compat"]
git-tree-sha1 = "21622ffb05343e51bc5b95c3576a71b26183809d"
uuid = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"
version = "0.2.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Mocking]]
deps = ["Compat", "Dates", "InteractiveUtils", "Pkg"]
git-tree-sha1 = "bf12ee38e32cc0eac156abb6bd828a346deee80c"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
version = "0.5.5"

[[MySQL]]
deps = ["BinaryProvider", "Compat", "DataStreams", "DecFP", "Missings"]
git-tree-sha1 = "e8438339d21eccd88babb910934fd0b8808c6eb8"
repo-rev = "master"
repo-url = "https://github.com/JuliaDatabases/MySQL.jl.git"
uuid = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
version = "0.5.2+"

[[NamedTuples]]
git-tree-sha1 = "6374851ad4b15f2a20ac20637d38c550531fa684"
uuid = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
version = "4.0.2"

[[Nullables]]
deps = ["Compat", "InteractiveUtils", "Pkg"]
git-tree-sha1 = "3e0c90487ebaf7f14b9f39e817c5afca41869ccf"
uuid = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
version = "0.0.6"

[[OffsetArrays]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "7c4ca0f266081385e2ecf57fb210034f970cce5d"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "0.8.0"

[[OhMyREPL]]
deps = ["Crayons", "InteractiveUtils", "Markdown", "Pkg", "Printf", "REPL", "Test", "Tokenize"]
git-tree-sha1 = "e00d5394d110afe279101ffe10cebd11eaedcb8a"
uuid = "5fb14364-9ced-5910-84b2-373655c76a03"
version = "0.3.0"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "cc23c786049328c93138da14e7020a464d707a23"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "0.1.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[Revise]]
deps = ["Distributed", "FileWatching", "LibGit2", "OrderedCollections", "Pkg", "REPL", "Random", "Test", "Unicode"]
git-tree-sha1 = "d49990fc136cb88d5b48fb803bf5f44244e26b8d"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "0.5.4"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SQLite]]
deps = ["BinDeps", "DataFrames", "DataStreams", "Dates", "Homebrew", "LegacyStrings", "Libdl", "WeakRefStrings", "WinRPM"]
git-tree-sha1 = "746f7368960d994f77a92127db054cd9964e9fc7"
repo-rev = "master"
repo-url = "https://github.com/JuliaDatabases/SQLite.jl.git"
uuid = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
version = "0.5.0+"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "1cf00baba50536d254f02082c90b98d6e4e1f968"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.6.0"

[[StackTraces]]
git-tree-sha1 = "6d2e45507b6480790740c54203336bc668bb1f60"
uuid = "670d9266-7b14-5e98-a133-3b8c27ea9ed4"
version = "0.1.1"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[Syslogs]]
deps = ["Compat", "Nullables"]
git-tree-sha1 = "d3e512a044cc8873c741d88758f8e1888c7c47d3"
uuid = "cea106d9-e007-5e6c-ad93-58fe2094e9c4"
version = "0.2.0"

[[TableTraits]]
deps = ["IteratorInterfaceExtensions", "Test"]
git-tree-sha1 = "7dff93e0a753f5d5dfd288d321b533af1ea2dfef"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "0.3.0"

[[TableTraitsUtils]]
deps = ["DataValues", "IteratorInterfaceExtensions", "Missings", "TableTraits", "Test"]
git-tree-sha1 = "ae7e7f36706a3f33fd0ccd7b6b599006f837831b"
uuid = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
version = "0.2.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TimeZones]]
deps = ["Compat", "EzXML", "Mocking", "Nullables"]
git-tree-sha1 = "a2acbdd15b3dc5d874013790ef116809747de4ef"
uuid = "f269a46b-ccf7-5d73-abea-4c690281aa53"
version = "0.7.2"

[[Tokenize]]
deps = ["Printf", "Test"]
git-tree-sha1 = "a5c7b247ef35e6e9e5bc46c494a42f1a51627936"
uuid = "0796e94c-ce3b-5d07-9a54-7f471281c624"
version = "0.5.1"

[[TranscodingStreams]]
deps = ["Compat", "Random", "Test"]
git-tree-sha1 = "d10e1e4b8fb8c6c50a1458c8e0de8f7abd0fc144"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.5.3"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[WeakRefStrings]]
deps = ["Compat", "Missings"]
git-tree-sha1 = "bb0464e62baf3a0767340fbb51fed584159ad9b7"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "0.4.7"

[[WinRPM]]
deps = ["BinDeps", "Compat", "HTTPClient", "LibExpat", "Libdl", "Libz", "SHA", "URIParser"]
git-tree-sha1 = "43730fcfe2f4921e7cfe1c21a6fdfeabb7ee4d74"
uuid = "c17dfb99-b4f7-5aad-8812-456da1ad7187"
version = "0.3.2"

[[YAML]]
deps = ["Codecs", "Compat"]
git-tree-sha1 = "a81c4f46c19f0eb9abaa90f3112bf536c1cfa7f9"
uuid = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
version = "0.2.1"
