name = "SearchLight"
uuid = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "2.6.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Millboard = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DataFrames = "1"
Inflector = "1"
Intervals = "1.5.0"
JSON3 = "1.9"
Millboard = "0.2"
OrderedCollections = "1"
Reexport = "0.2, 1"
YAML = "0.4"
julia = "1"
