name = "SearchLight"
uuid = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
authors = ["Adrian Salceanu <e@essenciary.com>"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStreams = "9a8bc11e-79be-5b39-94d7-1ccc349a1a85"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DateParser = "c513aa4d-7626-5656-a882-4604be010eff"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Lumberjack = "ff7a09a4-2bbe-5ce1-96cb-a4b0cacc22b1"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Millboard = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
NamedTuples = "73a701b4-84e1-5df0-88ff-1968ee2ee8dc"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
